name: Check for vaccine availibilities

on:
  workflow_dispatch:

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run main
        run: yarn startGithubAction
        env:
          FREE_MOBILE_USER: ${{ secrets.FREE_MOBILE_USER }}
          FREE_MOBILE_PASS: ${{ secrets.FREE_MOBILE_PASS }}
      - name: Commit changes if needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add .
            git commit -m "Update data"
            git push origin main
          else
            echo "no changes";
          fi
